spring:
  application:
    name: smart-parking-core

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&stringtype=unspecified
    username: postgres.rrmhwltgofgtvxrmfxpl
#    password: Ksupabase05NTz
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate          # Dùng Flyway/Liquibase để quản lý schema
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: smart-parking-core
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.smartparking.*"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.smartparking: DEBUG
    org.springframework.kafka: INFO

# App custom config
app:
  jwt:
#    secret: SmartParkingSecretKey2026VeryLongStringForHS256AlgorithmSecurity
    expiration-ms: 86400000      # 24 giờ

  settings:
    file-path: ${SETTINGS_PATH:../python_edge_desktop/config/settings.json}

  sepay:
    webhook-secret: ${SEPAY_WEBHOOK_SECRET:change_me_in_production}
    bank-account: ${SEPAY_BANK_ACCOUNT:0123456789}
    bank-name: ${SEPAY_BANK_NAME:MB}
    account-name: ${SEPAY_ACCOUNT_NAME:CONG TY SMART PARKING}

  zns:
    access-token: ${ZNS_ACCESS_TOKEN:change_me_in_production}
    app-id: ${ZNS_APP_ID:change_me}
    template-otp: ${ZNS_TEMPLATE_OTP:1234}
    template-reminder: ${ZNS_TEMPLATE_REMINDER:5678}
    template-confirm: ${ZNS_TEMPLATE_CONFIRM:9012}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha


#supabase:
#  url: "https://rrmhwltgofgtvxrmfxpl.supabase.co"
#  anon-key: "sb_publishable_cS4urr2ZNRLPOi5ayfV1BA_xbBCvKHB" # Dùng để login/verify
#  service-role-key: "sb_secret_Ei_DI3U3VS7iLFb74hY4rg_67Bqo6B7" # Dùng cho quyền Admin (ví dụ: ép đổi pass)
#  jwt-secret: "a4694d3b-819b-4b87-9a7e-d6fbc7ae368"

