apiVersion: v1
kind: Secret
metadata:
  name: sps-backend-secrets
  namespace: default
type: Opaque
stringData:
  # Redis
  REDIS_PASSWORD: "[YOUR_REDIS_PASSWORD]"
  
  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://[YOUR_DB_HOST]:5432/postgres?sslmode=require&stringtype=unspecified"
  SPRING_DATASOURCE_USERNAME: "[YOUR_DB_USERNAME]"
  SPRING_DATASOURCE_PASSWORD: "[YOUR_DB_PASSWORD]"
  
  # Supabase Auth
  SUPABASE_JWK_URI: "https://[YOUR_PROJECT_REF].supabase.co/auth/v1/.well-known/jwks.json"
  SUPABASE_URL: "https://[YOUR_PROJECT_REF].supabase.co"
  SUPABASE_ANON_KEY: "[YOUR_SUPABASE_ANON_KEY]"
  SUPABASE_SERVICE_ROLE_KEY: "[YOUR_SUPABASE_SERVICE_ROLE_KEY]"
  SUPABASE_JWT_SECRET: "[YOUR_SUPABASE_JWT_SECRET]"

  # Integrations
  TWILIO_ACCOUNT_SID: "[YOUR_TWILIO_ACCOUNT_SID]"
  TWILIO_AUTH_TOKEN: "[YOUR_TWILIO_AUTH_TOKEN]"
  SEPAY_WEBHOOK_SECRET: "[YOUR_SEPAY_WEBHOOK_SECRET]"

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-pull-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"https://registry-1.docker.io":{"username":"[YOUR_DOCKER_USERNAME]","password":"[YOUR_DOCKER_PAT]","auth":"[BASE64_OF_USERNAME:PASSWORD]"}}}
