apiVersion: apps/v1
kind: Deployment
metadata:
  name: sps-desktop-deployment
  labels:
    app: sps-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sps-desktop
  template:
    metadata:
      labels:
        app: sps-desktop
    spec:
      containers:
        - name: desktop-ai-container
          image: sps-desktop-app:4300aaa2e1deb999ea8d6f3ef5b16449d8aae9c3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8550

          env:
            - name: API_BASE_URL
              value: "http://sps-backend-service:8080/api/v1"

---
apiVersion: v1
kind: Service
metadata:
  name: sps-desktop-service
spec:
  type: ClusterIP
  selector:
    app: sps-desktop
  ports:
    - protocol: TCP
      port: 8550
      targetPort: 8550
