spring.data.redis.url=rediss://default:${REDIS_PASSWORD}@touched-insect-127463.upstash.io:6379
spring.data.redis.timeout=3000ms

spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=2000ms