apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sps-backend-deployment
  labels:
    app: sps-backend
spec:
  selector:
    matchLabels:
      app: sps-backend
  template:
    metadata:
      labels:
        app: sps-backend
    spec:
      serviceAccountName: sps-backend-sa
      automountServiceAccountToken: false
      containers:
        - name: backend-container
          image: ichbineinhund/srs-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: sps-config
            - secretRef:
                name: sps-backend-secrets
          env:
            - name: APP_TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: sps-backend-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: APP_TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sps-backend-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: APP_SEPAY_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sps-backend-secrets
                  key: SEPAY_WEBHOOK_SECRET
            - name: APP_TWILIO_FROM_NUMBER
              value: "+15075545747"
            - name: APP_DEMO_ADMIN_PHONE
              value: "+84399486270"
            - name: APP_DEMO_OTP_EXPIRATION_MINUTES
              value: "15"
            - name: APP_DEMO_OTP_MAX_TRY
              value: "5"
  strategy:
    canary:
      steps:
        - setWeight: 20
        # Tự động gọi Bài kiểm tra sức khỏe
        - analysis:
            templates:
            - templateName: success-rate
        - setWeight: 50
        - pause: {duration: 10m}

---
apiVersion: v1
kind: Service
metadata:
  name: sps-backend-service
spec:
  # Bịt lỗ hổng: Chỉ cho phép nội bộ K8s (Ingress) gọi vào, cấm ngoài gọi
  type: ClusterIP
  selector:
    app: sps-backend
  ports:
    - protocol: TCP
      port: 8080        # Cổng giao tiếp nội bộ trong K8s
      targetPort: 8080  # Cổng thực tế của Java App
