apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sps-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.sps.local
        - kiosk.sps.local
        - mobile.sps.local
        - ai.sps.local
      secretName: sps-tls-secret
  rules:
    - host: api.sps.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sps-backend-service
                port:
                  number: 8080

    - host: kiosk.sps.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sps-kiosk-service
                port:
                  number: 80

    # 3. Khách gõ mobile.sps.local -> Vứt cho Flutter Mobile
    - host: mobile.sps.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sps-mobile-service
                port:
                  number: 80
