nameReference:
- kind: ServiceAccount
  fieldSpecs:
  - kind: Rollout
    path: spec/template/spec/serviceAccountName

- kind: AnalysisTemplate
  fieldSpecs:
  - kind: Rollout
    path: spec/strategy/canary/steps/analysis/templates/templateName

- kind: ConfigMap
  fieldSpecs:
  - kind: Rollout
    path: spec/template/spec/containers/envFrom/configMapRef/name

- kind: Secret
  fieldSpecs:
  - kind: Rollout
    path: spec/template/spec/containers/envFrom/secretRef/name

- kind: SealedSecret
  fieldSpecs:
  - kind: Rollout
    path: spec/template/spec/containers/envFrom/secretRef/name
