apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - network-policy.yaml
  - sps-sealed-secret.yaml
  - backend.yaml
  - kiosk.yaml
  - mobile.yaml
  - ingress.yaml
  - ingress-logging.yaml
  - hpa-backend.yaml
  - rbac.yaml
  - network-policy.yaml
  - sps-sealed-secret.yaml
  - analysis-template.yaml
