apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.5.19
    helm:
      values: |
        resources:
          limits:
            cpu: <YOUR_CPU_LIMIT_e.g_100m>
            memory: <YOUR_MEM_LIMIT_e.g_128Mi>
          requests:
            cpu: <YOUR_CPU_REQUEST_e.g_50m>
            memory: <YOUR_MEM_REQUEST_e.g_64Mi>
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
